### ISSUE TITLE
[ImaAdPlayer] Possibility to change ad tag dynamically

### ISSUE THREAD

**Issue by oFilipMalinowski** [kslimani/clappr-ima-plugin#10]
Feature request upcoming!

In our implementations we do not recreate Clappr player. We initialize it only once, keep it as permanent part of DOM and then just manipulate the source. Therefore (afaik) it is not possible to change VAST url dynamically (based on what I understood from your ImaAdPlayer source). It would be quite handy for us to be able to load new VAST source on demand, i.e. using something like this
`playerObject.core.getPlugin("ima-plugin").loadTag(res)`
Would it be possible to create and expose such API?

**Comment by kslimani** [comment]
@oFilipMalinowski : have you tried with the `Clappr.configure()` method ?

For example, take a look at [dev. page](https://github.com/kslimani/clappr-ima-plugin/blob/master/public/index.html#L107) javascript code.

**Comment by oFilipMalinowski** [comment]
Thanks, works! Can be closed.
