### ISSUE TITLE
Video duration in metadata (?)

### ISSUE THREAD

**Issue by aFilipMalinowski** [kslimani/clappr-ima-plugin#13]
**Environment 1**
Google Chrome 76
Clappr (Newest)
IMA SDK plugin for Clappr (Newest)

**Environment 2**
Chrome 73 based browser (NFBE)
Clappr (Newest)
IMA SDK plugin for Clappr (Newest)

**Issue**
When we're preparing some VAST file with media that possibly has the duration metadata not at the beginning of the file, we reach some kind of timeout with IMA. On video screen we get then **html5_video:4** error. Do you have any idea what could be going on?

**Comment by kslimani** [comment]
@oFilipMalinowski  : do you have a sample page to share reproducing the issue ?

**Comment by oFilipMalinowski** [comment]
We're using our own browser based on Chromium called NFBE.
I will try to provide you an application with this browser for testing purposes.
However please hang up with it as it might be that the problem lays on our browser implementation.
I will keep you updated. Many thanks for help.

**Comment by kslimani** [comment]
A browser issue is my first though too, because the error code 4 on html5 video element is [MEDIA_ERR_SRC_NOT_SUPPORTED](https://developer.mozilla.org/en-US/docs/Web/API/MediaError#Properties).

_(The most common issue is that browser has no mp4 codec)_.

**Comment by aFilipMalinowski** [comment]
Okay. It went out to be problem with our browser integration. Can be closed. Sorry for bothering!
