### ISSUE TITLE
Events on adStarted, adEnded

### ISSUE THREAD

**Issue by aFilipMalinowski** [kslimani/clappr-ima-plugin#14]
I have one request.
In our UI we have one feature called `idle mode`. When conditions for `idle mode` are reached, we load different playlist to clappr. Requirement is - no user interaction within period of time after playback was stopped, paused, ended.
When we're playing ads, playback is paused and ads are playing. When ads are quite long, conditions for `idle mode` can be reached.
Therefore could it be possible for you to provide an interface (some events) when ad started to play, when ad finished playing, etc?

**Comment by kslimani** [comment]
@aFilipMalinowski all these events already exists and are provided by internal ad player instance. _(it is just currently poorly documented, shame on me...)_

Take a look at ad player [project test page](https://github.com/kslimani/ima-ad-player/blob/master/public/index.html).

You can retrieve ad player instance using `onAdPlayerReady` plugin option, then bind required events.

**Comment by aFilipMalinowski** [comment]
Yes, I see it. Thank you very much for help!

**Comment by kslimani** [comment]
@aFilipMalinowski take also a look at [code here](https://github.com/kslimani/clappr-ima-plugin/blob/master/public/index.html#L86) _(commented onAdPlayerReady example)_
