### ISSUE TITLE
No EXTM3U delimiter issue

### ISSUE THREAD

**Issue by aFilipMalinowski** [kslimani/clappr-ima-plugin#15]
Sometimes when I'm playing the same content with preroll, after preroll plays till end Clappr is informing about an error "no extm3u delimiter". Does not happen when I do not use preroll. Any idea what could be wrong?

Edit: happens for any kind of content - mp4, m3u8, ogg. Clappr shows an error hls:networkError_manifestParsingError

**Comment by kslimani** [comment]
The issue you describe _seems_ to be related to hlsjs playback.

Do you have a page reproducing this issue to share ? or any steps to reproduce the issue ?

**Comment by aFilipMalinowski** [comment]
I have no clear steps to reproduce that yet. I'll continue with testing to see if I'll manage to find some.

**Comment by aFilipMalinowski** [comment]
Hmm. Clearly I am having issues when `recycleVideo` is set when using IMA plugin. When time allows, I will prepare some example of our implementation and provide it to you. Currently have lots to do so it might take a while. Thank you for the support by the way!

**Comment by kslimani** [comment]
I close this issue for now.

Feel free to re-open it if you are able to reproduce and provide more feedback.
