### ISSUE TITLE
Event object in adPlayer events

### ISSUE THREAD

**Issue by aFilipMalinowski** [kslimani/clappr-ima-plugin#16]
Can you tell me how can I get information from IMA SDK if the ad is a preroll, postroll?

Something similar to this in VideoJs.
```
ima.addEventListener(google.ima.AdEvent.Type.COMPLETE, evt => {
  if (evt.getAd().getAdPodInfo().getPodIndex() == -1) { //-1 is postroll
    this.events.onPause();
  }
});
```

**Comment by aFilipMalinowski** [comment]
In your Ima Player I have access to it (I guess) in this scope

```
adPlayer.on('ad_end', (evt) => {
});
```

**Comment by kslimani** [comment]
Following the provided VideoJS sample code, with clappr-ima-plugin it should be something like :+1: 

```javascript
var player = new Clappr.Player({

  // ...

  plugins: [
    ClapprImaPlugin,
  ],
  imaPlugin: {
    onAdPlayerReady: function (adPlayer) {
      adPlayer.on('complete', function(o) {
        if (o.data.getAd().getAdPodInfo().getPodIndex() == -1) {
          // ...
        }
      });
    },

    // ...

  },
});
```

**Comment by kslimani** [comment]
See also AdPodInfo [getPodIndex](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdPodInfo.getPodIndex) method documentation.

**Comment by aFilipMalinowski** [comment]
Great! Thanks
