### ISSUE TITLE
vpaidMode

### ISSUE THREAD

**Issue by inside83** [kslimani/clappr-ima-plugin#33]
Hi
Super lame/noob question:

What's vpaidMode and why is it's value 2 in the demo?

**Comment by kslimani** [comment]
`vpaidMode` is [adPlayer](https://github.com/kslimani/ima-ad-player/blob/master/docs/config.md#ad-player-configuration-options) configuration option which is same as [ima sdk vpaidMode](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima#.VpaidMode). (2 is "ENABLED" which is default)
_(internally it simply call setVpaidMode and pass the value)_

**Comment by inside83** [comment]
Oh, got it 👍
Thanks for clarification.
