### ISSUE TITLE
Vod video HLS

### ISSUE THREAD

**Issue by ctaity** [kslimani/clappr-ima-plugin#5]
This plugin is tested with HLS VOD ?

**Comment by kslimani** [comment]
It should work with HLS VOD.

Though, it seems there is a little regression with Firefox desktop _(with HLS VOD)_. I will investigate on this issue ASAP.

**Comment by ctaity** [comment]
I having multiple problems with hls vod. 
You can test with this m3u8: https://cdn-vod.tvpublica.com.ar/out/2019/06/24/rJSGGORyB/main.m3u8
And i am using the tag of demo page. 
After preroll, the video never starts, keep buffering with the 3 points on the screen.

**Comment by kslimani** [comment]
You are correct, there is an issue with HLS VOD. It works with Google Chrome,but i have similar issue with Firefox (desktop) and Safari (on mac).

I am pretty sure it worked previously. I will investigate on this issue.

**Comment by kslimani** [comment]
@ctaity i released a temporary workaround. Could you try with `https://cdn.jsdelivr.net/npm/clappr-ima-plugin@0.2.3/dist/clappr-ima-plugin.min.js` (set version in url as jsDelivr may take some hours to update cache).

**Comment by ctaity** [comment]
works now !!!!! Thanks

**Comment by ctaity** [comment]
1 question, on live streaming still dont work?

**Comment by kslimani** [comment]
pre-roll should work on live streaming
_(midroll and postroll is not supported with live stream source)_.

**Comment by YuThandar** [comment]
@kslimani  clappr-ima-plugin@0.2.3, this version is autoPlay video but mid-roll ad finished keep on running post-roll ad.Skipped the remain video play time go to post-roll ad.

**Comment by kslimani** [comment]
@YuThandar could you please try with the current latest version 0.2.11 ?

If this does not still works, please open a new issue, providing steps to reproduce it.

**Comment by YuThandar** [comment]
@kslimani  I'm Ok in version 0.2.4.This version is everything Ok. Latest version is not supported autoPlay after play ads the video pause. Thank you Sir.

**Comment by kslimani** [comment]
@YuThandar could you please elaborate about the 0.2.11 not working ? _(if something is broken, i should be able to fix it)_

**Comment by YuThandar** [comment]
@kslimani Firstly,the pre-roll ad autoPlay is OK and then the ad finished.The video automatically pause.You are going to test with m3u8 file.

**Comment by kslimani** [comment]
@YuThandar i am testing locally with  HLS source and i can't reproduce this issue.

Are you experiencing this issue on mobile device or desktop ? _(which os version and browser version)_

**Comment by YuThandar** [comment]
@kslimani desktop is OK. Only mobile device this error.

**Comment by kslimani** [comment]
@YuThandar do you have `recycleVideo` Clappr playback option set to true with mobile ?

For example :

```javascript
var player = new Clappr.Player({
  // [...]
  playback: {
    playInline: true,
    recycleVideo: Clappr.Browser.isMobile,
  },
});
```

**Comment by YuThandar** [comment]
@kslimani  No, I did not test this feature. I will test this feature tomorrow.

**Comment by YuThandar** [comment]
@kslimani  Yes, I did insert this feature in my code.And I used IMA  latest version can't support in mobile  
device.

**Comment by kslimani** [comment]
I did some additional tests on mobile devices but i can't reproduce the issue you described _(ie: video is paused after ad)_. Would you mind sharing the code you are using to create the player and also provide which mobile model / operating system it is ?

**Comment by YuThandar** [comment]
@kslimani  Sorry Sir, for late replying.Please, see the below my code link. Please check this code in mobile device.After 10sec preroll and then the video stop.This is IMA latest version.
https://staging.duwun.com.mm/static/clappr/clappr-latest.html

**Comment by kslimani** [comment]
@YuThandar thank you for providing the link. I was able to reproduce your issue locally. I created [a new issue](https://github.com/kslimani/clappr-ima-plugin/issues/19) to continue this conversation.
