### ISSUE TITLE
How to add Ad Controls?

### ISSUE THREAD

**Issue by GiriAakula** [kslimani/clappr-ima-plugin#55]
There seems to be no documentation on how to add **ad controls** like play, pause and mute.

In the current implementation that is shown on the example player ad controls are not coming.

Take a look at the screenshot which demonstrates the same.

![Screenshot 2022-03-11 at 11 51 33 AM](https://user-images.githubusercontent.com/38908324/157813807-59aed3d4-15c4-4061-a26b-3bc68d293444.png)

Please explain how can I add play-ad and pause-ad button on ads, so that users can play and pause ad whenever they need.

**Comment by kslimani** [comment]
Hi,

As far as i know, ad controls are not part of Google Ima Ad Player. (HTML5 SDK), you have, indeed,  to implements yours.

I released a new version of this plugin which should ease you to create your own custom controls.

Just use the `onAdPlayerReady` plugin option to [retrieve ad player instance](https://github.com/kslimani/clappr-ima-plugin/blob/master/public/index.html#L91) to bind specific events to [add/display/hide your custom controls](https://github.com/kslimani/ima-ad-player/blob/master/public/index.html#L262).

**Comment by kslimani** [comment]
I forgot to mention you can also use VPAID to add custom controls.

**Comment by GiriAakula** [comment]
Thanks for the response. I am thinking to implement my own controls as you mentioned.
