### ISSUE TITLE
Support for @clappr/player latest version

### ISSUE THREAD

**Issue by utilsites** [kslimani/clappr-ima-plugin#63]
Like discussed [here](https://github.com/clappr/clappr/issues/2042#issuecomment-1382179670), clappr changed to a new project:
[@clappr/player](https://www.npmjs.com/package/@clappr/player).

The [old project](https://www.npmjs.com/package/clappr) on npm now has this message:
_This package has been deprecated, Author message:
This version is no longer supported. Please use the @clappr/player versions instead._

Can this clappr IMA plugin have a new version (maybe better on other project to don't brake latest), that is compatible with @clappr/player ?
Or it's already compatible? Sorry, it's a bit confusing.

**Comment by kslimani** [comment]
Hello, i released a new version of the plugin which should support Clappr 0.4+
Please note this is experimental (i could not test on every devices, like phones or tablets).

**Comment by utilsites** [comment]
Nice, thanks!
Can you also confirm if the lates version of [clappr IMA plugin](https://www.npmjs.com/package/clappr-ima-plugin?activeTab=versions) is compatible with the [clappr old version](https://www.npmjs.com/package/clappr)?
It seems so, but I'm not sure.
Maybe need to lock the version for the previous one, while don't migrate to clappr player last version.

**Comment by kslimani** [comment]
I used a 0.5.0 tag (from previous 0.4.6) to mark the change. But it should be still backward compatible because i did not made any major changes (only implemented required methods, by Clappr 0.4+).

**Comment by utilsites** [comment]
Ok thanks for the information. For now I will keep the previous clappr version, but later will migrate.
