### ISSUE TITLE
[Clappr | MP3] Possibility to support audio files

### ISSUE THREAD

**Issue by oFilipMalinowski** [kslimani/clappr-ima-plugin#8]
**Environment**
Google Chrome 75
Clappr 0.3.6 (Newest)
IMA SDK plugin for Clappr / IMA SDK plugin preroll only

**Description**
Is it possible to support ads when playing audio content? Seems to be reasonable usecase to make the user to listen to some audio advert when playing some content.

**Test**

    VAST: https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=
    Source: https://file-examples.com/wp-content/uploads/2017/11/file_example_MP3_5MG.mp3

I tested it with sample audio and sample VAST tag. Seen behaviour is that both advert and content start to play together. Once advert comes to end, content starts to play from the beginning.

**Comment by kslimani** [comment]
@oFilipMalinowski  I have released a new version which should support audio only.

I have done some testing with the provided mp3 source and vast linear preroll tag and it seems to work the following in most cases :

* on desktop linux, Chrome and Firefox are displaying pre-roll (and then mp3 source is played)
* on desktop Mac OSX, Safari is not displaying pre-roll video but is playing pre-roll audio (and then mp3 source is played)
* on android (Samsung Galaxy S5), Chrome is not displaying pre-roll video but is playing pre-roll audio (and then mp3 source is played)
* on android (Samsung Galaxy S5), Samsung browser is not displaying pre-roll video but is playing pre-roll audio (and then mp3 source is played)
* on android (Samsung Galaxy Tab 4), Chrome is not displaying pre-roll video but is playing pre-roll audio (and then mp3 source is played)
* on iOS (iPad mini), Safari is not displaying pre-roll video but is playing pre-roll audio (and then mp3 source is played)

My recommendations are to use "still image" video pre-roll for audio only source.

**Comment by oFilipMalinowski** [comment]
> displaying / not displaying pre-roll video

This is actually acceptable behaviour. Result is good as I don't expect to show any video when playing audio-only content. For me it's more logical to keep video ads with video content, and audio ads with audio content only.

I tested it a bit with some content from my MediaServer and it is working good.

Can be closed. Thanks!
