### ISSUE TITLE
not working on IOS

### ISSUE THREAD

**Issue by Alexdrr** [kslimani/clappr-ima-plugin#9]
Hello! THis plugin not work on iOS, by click on video opened  iphone player (not web). pls tell me how to fix this issue?

**Comment by kslimani** [comment]
@Alexdrr does your Clappr playback configuration has `playInline` set to true ?

For example :

```javascript
var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  playback: {
    playInline: true,
  },
  // [...]
});
```

**Comment by Alexdrr** [comment]
> @Alexdrr does your Clappr playback configuration has `playInline` set to true ?
> 
> For example :
> 
> ```js
> var player = new Clappr.Player({
>   source: 'http://clappr.io/highline.mp4',
>   playback: {
>     playInline: true,
>   },
>   // [...]
> });
> ```

thanks so much! it works!

**Comment by Alexdrr** [comment]
> @Alexdrr does your Clappr playback configuration has `playInline` set to true ?
> 
> For example :
> 
> ```js
> var player = new Clappr.Player({
>   source: 'http://clappr.io/highline.mp4',
>   playback: {
>     playInline: true,
>   },
>   // [...]
> });
> ```

https://ibb.co/j3rdKyK

By clicking on player preroll stopped, but by clicking Learn More it open in browser link, tell me pls, how i can increase this plase to fullscreen? need by clicking on screen  - opens ads link

**Comment by kslimani** [comment]
Ad click is not supported on iOS in fullscreen mode. Please read [IMA Support and Compatibility](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility) page.

**Comment by Alexdrr** [comment]
> Ad click is not supported on iOS in fullscreen mode. Please read [IMA Support and Compatibility](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility) page.

yes, i know about fullscreen mode with no ad click. but after first click player show preroll and have ad link in right top side. how i can increase clickable place to full player size?

**Comment by kslimani** [comment]
@Alexdrr all GUI elements displayed during ad playback are not added or handled by this plugin.
_(it is added and handled by IMA SDK)_.

You should be able to add [custom click tracking zone](https://developers.google.com/interactive-media-ads/docs/sdks/html5/tracking_clicks) using ImaPlayer events.

Use the `onAdPlayerReady` plugin option to retrieve ImaPlayer instance and bind events :

```javascript
var player = new Clappr.Player({
  // [...]
  onAdPlayerReady: function (adPlayer) {
    adPlayer.on('EVENT_NAME', function(o) {
      // [...]
    });
  },
});
```

To get available events, take a look at [ima-ad-player development page](https://github.com/kslimani/ima-ad-player/blob/master/public/index.html#L94).
_(Note: ImaPlayer is an ad player wrapper for IMA SDK library used internally by this plugin)_

**Comment by kslimani** [comment]
In addition, it seems that adding custom click element for clickthroughs require to use `opt_clickTrackingElement` optional argument in Google IMA [AdDisplayContainer constructor](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdDisplayContainer).

This is not currently handled by ima-ad-player. But if it is a requirement for you, i can add a new option to allow such customization.

**Comment by kslimani** [comment]
I released a new version with new [ima-ad-player](https://github.com/kslimani/ima-ad-player) `clickTracking` configuration option.

Feel free to open a new issue if you still having trouble with click tracking.
